global:
  config_name: article_extraction_businessinsider.com

pipeline:
  configs:

    init:
      files_produced:
        page_index: "/hypercoref/working_dir/page_seeding/businessinsider.com.csv"

    postprocess_hyperlinks:
      netloc_whitelist:
        - "businessinsider.com"