global:
  config_name: article_extraction_huffpost.com

pipeline:
  configs:

    init:
      files_produced:
        page_index: "/hypercoref/working_dir/page_seeding/huffpost.com.csv"

    postprocess_hyperlinks:
      netloc_whitelist:
        - "huffpost.com"