global:
  config_name: manual_analysis


pipeline:
  stages:
    - module: python.pipeline.common.dummy_feeder_stage
      name: init
    - module: python.data.pipeline.analysis.anchors_into_separate_txt_files

  configs:
    init:
      files_produced:
        page_infos: "..."
        hyperlinks: "..."
        sentences: "..."