global:
  config_name: article_extraction_nrc.nl

pipeline:
  configs:

    init:
      files_produced:
        page_index: "/hypercoref/working_dir/page_seeding/nrc.nl"

    postprocess_hyperlinks:
      netloc_whitelist:
        - "nrc.nl"